name: Build uYouEnhanced

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 リポジトリをクローン
      uses: actions/checkout@v4

    - name: 🔧 必要なパッケージをインストール
      run: |
        sudo apt update
        sudo apt install -y make clang llvm dpkg unzip curl git

    - name: 🔧 libtapi-dev をソースからインストール
      run: |
        sudo apt update
        sudo apt install -y build-essential
        git clone https://github.com/apple/swift.git
        cd swift
        ./utils/update_submodules.py --revision 0.49
        mkdir build
        cd build
        cmake ..
        make -j
        sudo make install

    - name: 🔨 ldid をビルドしてインストール
      run: |
        git clone https://github.com/ProcursusTeam/ldid.git
        cd ldid
        make
        sudo cp ldid
